const verificarNumero = (numeros) =>{
    return new Promise ((resolve, reject) => {
        let numeroaleatorio = Math.floor(Math.random ());
        resolve(1);
        numeroaleatorio*10;
    })
}

retornarPromise().then(console.log);

//erro